version: '3.9'
services:
  backend: 
    container_name: backend
    image: victhun/backend
    restart: always
    environment:
      - DATABASE_URL="postgresql://ace:password@ace-development.ru:5432/db?schema=public"
    ports:
      - "3005:3005"
  frontend:
    container_name: frontend
    image: victhun/frontend
    restart: always
    ports:
      - "3000:3000"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 backend frontend